services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: conceptual2002
      POSTGRES_DB: library_kit_db
    ports:
      - "5431:5432"  # host:container
    volumes:
      - postgres_data:/var/lib/postgresql/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: rental-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./shared:/usr/src/shared

volumes:
  postgres_data:
  redis_data:
